### ISSUE TITLE
Program doesn't support quote markers in the textgrid

### ISSUE THREAD

**Issue by Neigelily** [maxime-fily/TXTGRD2XML#1]

**Comment by maxime-fily** [comment]
This is an issue often met with xml, any quote marker will be in conflict with the syntax. The same issue could be opened on inferior or superior sign. The issue has been addressed for textgrid information (new release, upcoming). Concerning the information in tables, until now I found it more efficient to avoid using the double quote in the txt input, but I'll eventually incorporate the quote support for the txt input (when I have time).

**Comment by maxime-fily** [comment]
solved with new commit.
